# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AVPlayer1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AVPlayer1
  pod 'Alamofire'
  pod 'RealmSwift' 
  
end
